### ISSUE TITLE
factories 

### ISSUE THREAD

**Issue by Perfect-Web** [Payum/PayumModule#11]
there is no way to inject the payments or storages from the service locator, this is a HUGE minus,  it renders it unusable since you cant set the doctrine manager into the `Payum\Core\Bridge\Doctrine\Storage\DoctrineStorage` for example

**Comment by makasim** [comment]
It is possible.

**Comment by Perfect-Web** [comment]
the `$this->serviceLocator` is null where you pointed, and it throws a fatal error

**Comment by Perfect-Web** [comment]
the servicelocator is set at line 31, which is to late

**Comment by makasim** [comment]
Okay, then there must be a way to inject it earlier.
