### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method Payum\PayumModule\Registry\ServiceLocatorAwareRegistry::getStorage()

### ISSUE THREAD

**Issue by bMahadevan** [Payum/PayumModule#28]
I followed your doc to do the implementation but getting the undefined method error. 

`composer require "payum/payum-module:*@stable" "payum/paypal-express-checkout-nvp:*@stable" "payum/omnipay-bridge:*@stable"`

config
-------------------
```
use Payum\Core\Storage\FilesystemStorage;
use Payum\Paypal\ExpressCheckout\Nvp\PaypalExpressCheckoutGatewayFactory;
use Payum\Stripe\StripeJsGatewayFactory;
use Payum\OmnipayBridge\OmnipayGatewayFactory;

$paypalFactory = new PaypalExpressCheckoutGatewayFactory();
$omnipayFactory = new OmnipayGatewayFactory();

return array(
    'payum' => array(
        'token_storage' => new FilesystemStorage(
            __DIR__.'/../../data/payment',
            'App\Model\PaymentSecurityToken',
            'hash'
        ),
        'payments' => array(
            'paypal_ec' => $paypalFactory->create(array(
                'username' => 'xxx',
                'password' => 'xxx',
                'signature' => 'Axxx',
                'sandbox' => true
            )),
            'stripe_via_omnipay' => $omnipayFactory->create([
                'type' => 'Stripe',
                'apiKey' => 'dfdfd',
                'testMode' => true,
            ]),
        ),
        'storages' => array(
            'Matchmaker\Model\PaymentDetails' => new FilesystemStorage(
                __DIR__.'/../../data/payment',
                'App\Model\PaymentDetails',
                'id'
            )
        ),
    ),
);
```

if the payments is changed to gateways 'payum' could not be instantiated exception thrown. 

Controller:
`$storage = $this->getServiceLocator()->get('payum')->getStorage('Matchmaker\Model\PaymentDetails');`

I am not sure PayumModule is still working with your stable code. Can you take a look at doc and guide me to fix the issue.

Thank you,

**Comment by makasim** [comment]
PayumModule 0.15 works with Payum/Core 0.15. It was never tested with 1.x and newer and most likely does not work with it, I am completely sure it does not. 

So you have to:

* Make sure the payum packages installed have 0.15 version 

* Setup it accding to 0.15 docs https://github.com/Payum/PayumModule/blob/0.15.0/docs/get-it-started.md and https://github.com/Payum/Core/blob/0.15/Resources/docs/get-it-started.md

* It should not be hard to adopt a 1.0 version (there are only slight changes). So we can release it too.

**Comment by bMahadevan** [comment]
Thank you. That worked. I have issues with payum/omnipay-bridge now. It's getting invalid API key error. I'll debug that.

**Comment by makasim** [comment]
What omnipay bridge are you trying to use?

**Comment by bMahadevan** [comment]
sorry missed your message. it's working now. I hope I had a wrong version.
