### ISSUE TITLE
Sofort:Class 'Sofort\SofortLib\Multipay' not found

### ISSUE THREAD

**Issue by shoaibgits** [Payum/PayumModule#32]
I am trying to integrate the pa-yum So-fort Method in Zend Framework 2 I Have create the Controller method like this:

    namespace Reisesparer\Controller;

    use Payum\Core\Request\GetHumanStatus;
    use Zend\Mvc\Controller\AbstractActionController;
    use Zend\Di\ServiceLocator;
    use Zend\View\Model\JsonModel;
    use Zend\View\Model\ViewModel;
    use Sofort\SofortLib;

    class PaymentController extends AbstractActionController
    {
     public function sofortAction()
    {
        $storage = $this->getServiceLocator()->get('payum')->getStorage('Payum\Sofort\SofortLib\Sofortueberweisung');
       $configkey = '12345:12345:5dbdad2bc861d907eedfd9528127d002';
       
       $Sofortueberweisung = new Sofortueberweisung($configkey);
       $Sofortueberweisung->setAmount(10.21);
       $Sofortueberweisung->setCurrencyCode('EUR');
       $Sofortueberweisung->setReason('Testueberweisung', 'Verwendungszweck');
      
  

    $Sofortueberweisung->sendRequest();

    }

And I got the error: 

     Class 'Sofort\SofortLib\Multipay' not found in Payum\Sofort\SofortLib\Sofortueberweisung.php

How I can Fix this one?

**Comment by makasim** [comment]
I've just tested the Sofort in the [sandbox](https://github.com/makasim/PayumBundleSandbox). It works fine. I bet you had problems with autoloading.
