### ISSUE TITLE
Update for payum core 1.4.* ?

### ISSUE THREAD

**Issue by kristian-b** [Payum/PayumModule#34]
Hello,

we would like to get the benefit [of that bugfix](https://github.com/Sylius/Sylius/issues/3494#issuecomment-176677856) and want to upgrade our system to payum core 1.4.x. But this requirement fails while we install payum/payum-module:

```
 - Conclusion: don't install payum/payum 1.4.x-dev
    - payum/payum-module 0.15.0 requires payum/core 0.15.*@dev -> satisfiable by payum/payum[0.15.4], payum/core[0.15.1, 0.15.3, 0.15.x-dev].
    - Can only install one of: payum/payum[1.4.3, 0.15.4].
    - don't install payum/core 0.15.1|don't install payum/payum 1.4.3
```

It is planned to support payum core 1.4.x with tha module?

That would be great. Thank you.

Regards

**Comment by makasim** [comment]
I am not going to do it cuz I am not using zend anywhere. If someone does it I review\merge it.

**Comment by zaibi099** [comment]
Its updated and verified. Here is the fork pull request i made.
https://github.com/Payum/PayumModule/pull/35
